import csv
import os

rows = [
    {
        "id": "help_1",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_1",  # placeholder; you can replace with real URLs later
        "timestamp": "2019-05-04",
        "title": "I cant find my find my photos anywhere. Its like they're there, but blank.",
        "text": "I can't find my photos. It's like they're there but blank. Really don't know what to do. I had very important pix, that can't be recovered.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_2",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_2",
        "timestamp": "2023-06-06",
        "title": "Finding photos by notes on them",
        "text": "Hello!\nUntil recently I could find photos in the Google photos app by searching the notes I previously wrote to them individually, and it would find all the pictures with this note.\nNow this doesn't work anymore. Do you possibly know what the problem here could be? Would be very thankful for help!\nKind Regards\nJustin (loyal Google phone user)",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_3",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_3",
        "timestamp": "2024-02-08",
        "title": "Tagged people search issue on google photos",
        "text": "So issue is when I add person I can't find it through search. When I press + button to add person on one picture it's added. But when I try to add the same person on different photo I go to serch the person but It can't be found. So I do the same manual adding. I type a name and when I press add, google photos says \"is this the same person?\" but every time I try to find it it doesn't exist",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_4",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_4",
        "timestamp": "2020-04-22",
        "title": "Few albums not listed but available only w search and downloading other albums giving HTTP 500 error",
        "text": "2 issues. When I go to albums tab on web or on photos app on Android, several albums are not shown / listed. They can only be seen when searched with album name. Secondly, when I tried to download albums on to my laptop, constantly getting following error \"video-downloads.googleusercontent.com is currently unable to handle this request.HTTP ERROR 500\". I am trying to download one by one album and not multiple albums. In the past 2 days, I could only download 2 albums without the above error. I have seen many users posting same download error with albums for past 2 years but it seems this problem is not yet resolved. I have tried downloading album from within photos website going to album section and another way I have tried is through photos archive website https://get.google.com/albumarchive",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_5",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_5",
        "timestamp": "2018-07-13",
        "title": "Hi - I can't find a specific person in the list of people when i go into try to search/view photos",
        "text": "Can't find the most frequent person (my husband) tagged in fav's or in general search/view photos",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_6",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_6",
        "timestamp": "2024-04-25",
        "title": "Google photos has stopped finding people and pets after it's initial search.",
        "text": "I have switched on face identification groups and after Google has done initial group suggestions, I've gone through and corrected the groups by removing incorrect people, etc. but now it isn't making any other suggestions and isn't adding other faces that are very clear in photos. When I go to photos that have people in them that aren't tagged, there isn't a people option to add them to the groups either.\nPlease can I have advice on how to make it recognise the faces and add them to the groups and also recognise new faces that it hasn't grouped yet.\nAll my photos are backed up.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_7",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_7",
        "timestamp": "",  # “4 days ago” – leave blank or approximate if you want
        "title": "Backed up all photos still not able to sort pictures by faces",
        "text": "Backed up all photos still not able to sort pictures by faces, or not able to find people",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_8",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_8",
        "timestamp": "",  # “5 days ago”
        "title": "Give a lot of information about this boy",
        "text": "I cant search him up on Google",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_9",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_9",
        "timestamp": "2026-09-29",
        "title": "Can not find my photo when searching using its caption.",
        "text": "I added a caption to my photo eh lock.\nLater I searched photos using keyword lock, no results found or irrelevant photos showed.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_10",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_10",
        "timestamp": "",  # “7 days ago”
        "title": "REGRESSION: Text-in-image search returns \"No results\" on ALL platforms",
        "text": "Searching for words that appear in my screenshots now returns \"No results. Try a synonym or more general keyword.\" This worked reliably until recently.\n\nSteps to reproduce:\n1. Search \"inflammation\" (with and without quotation marks)\n2. Result: \"No results\"\nExpected: dozens to hundreds of screenshots containing this exact word, which search used to find.\n\nScope:\n- Fails on web (Chrome, macOS), iPadOS app, and Android app. Because it fails on every platform, this looks like an account-level or server-side indexing problem, not a client bug.\n- Also fails with Gemini features / Ask Photos turned on and off.\n- The screenshots are still in my library. The text is clearly readable, and Lens can read it.\n\nImpact: My entire workflow depends on finding screenshots by exact keyword. It is completely blocked, and I have no workaround.\n\nPlease check whether text (OCR) indexing for my account has been dropped or disabled.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_11",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_11",
        "timestamp": "2026-09-28",
        "title": "There is no search option at people page, instead of scrolling give search by name option",
        "text": "Same as above",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_12",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_12",
        "timestamp": "2018-09-21",
        "title": "My photos are missing",
        "text": "I was looking for pictures of when my son was born and there are a lot of them missing that I know were there. I can't remember the last time I looked at them but they were imported in ever since moving from Picasa to Google Photos.\nI have noticed around 2016 the pictures start to thin out as it goes further back.\n\nPlease help find my children's photos.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_13",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_13",
        "timestamp": "2018-08-27",
        "title": "Why can't I see or find all photos that are in my activity?",
        "text": "There's nothing else to try on my end.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_14",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_14",
        "timestamp": "2018-08-24",
        "title": "What search syntax allows searches for multiple faces but no others (ie John & Jane and no others)",
        "text": "I am able to find multiple faces by using syntax \"name1 and name2\" but do not know how to exclude pictures that include more than the two names searched.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_15",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_15",
        "timestamp": "2018-08-10",
        "title": "I lost my mothers 90th bithday celebration photos after my galaxyS8 factory reset itself Google phot",
        "text": "Checked my iPad to see if they uploaded after july 28th my moms pics were from Aug 5th I checked the trash",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_16",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_16",
        "timestamp": "2018-05-25",
        "title": "Where is a screen shot stored and how can I get the pic",
        "text": "I took a screen shot so I could post it on maps but I don't know how to retrieve it\n.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_17",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_17",
        "timestamp": "2018-08-16",
        "title": "I have photos precious 2 me, as others, going back to 2010. IS Google loosing them? Please be honest",
        "text": "I have tried wht was available to me n recommended. Loosing photos is like loosing memories n time.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_18",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_18",
        "timestamp": "2018-05-30",
        "title": "Hello. When you save a stylised photo, where does it go? Does it replace or duplicate?",
        "text": "When you save a stylised photo that Assistant created, where does it go? Does it sit in the album I created next to the original or does it replace the original? Or something else?",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
        "id": "help_19",
        "source": "help_community",
        "url": "https://support.google.com/photos/thread/HELP_19",
        "timestamp": "2018-04-17",
        "title": "Is it possible to automatically extract all photos from gmail and drop into google photos?",
        "text": "Have so many old photos buried in gmail that were sent as attachments dating back to 2005.  Would love to be able to seamlessly extract them and have them sync with google photos.",
        "retrieval_related": "",
        "incident": "",
        "what_remember": "",
        "what_missed": "",
        "emotion": "",
    },
    {
    "id": "help_20",
    "source": "help_community",
    "url": "https://support.google.com/photos/thread/HELP_20",
    "timestamp": "2018-09-24",
    "title": "The ability to add labels would be nice",
    "text": "As opposed to adding a description to each individual photo, if I could select multiple and give them a 'label' it would be nice for finding things (similar to labels in Gmail?) I realize this can also be accomplished by albums, but it helps makes things searchable.",
    "retrieval_related": "",
    "incident": "",
    "what_remember": "",
    "what_missed": "",
    "emotion": "",
    },
]

OUTPUT_FILE = "data/help_community_reviews.csv"

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

fieldnames = [
    "id", "source", "url", "timestamp", "title", "text",
    "retrieval_related", "incident", "what_remember", "what_missed", "emotion"
]

with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Saved {len(rows)} Help Community posts to {OUTPUT_FILE}")